/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema } from '../models/paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema';
import type { paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema } from '../models/paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class BeerOrderService {
    /**
     * Get all beer orders
     * Returns a list of all beer orders in the system.
     * @returns paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema Successfully retrieved the list of beer orders
     * @throws ApiError
     */
    public static getAllBeerOrders(): CancelablePromise<Array<paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beer-orders',
            errors: {
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Create a new beer order
     * Creates a new beer order in the system. The ID, version, createdDate, and updateDate fields will be ignored if provided.
     * @param requestBody Beer order object to be created
     * @returns paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema Successfully created a new beer order
     * @throws ApiError
     */
    public static createBeerOrder(
        requestBody: {
            /**
             * Unique identifier for the beer order. Read-only field generated by the system.
             */
            readonly id?: number;
            /**
             * Version number for optimistic locking. Read-only field incremented on each update.
             */
            readonly version?: number;
            /**
             * Date and time when the beer order was created. Read-only field.
             */
            readonly createdDate?: string;
            /**
             * Date and time when the beer order was last updated. Read-only field.
             */
            readonly updateDate?: string;
            /**
             * Reference information from customer.
             */
            customerRef?: string;
            /**
             * Payment amount for the order.
             */
            paymentAmount: number;
            /**
             * Status of the order (e.g., NEW, PAID, CANCELLED, INPROCESS, COMPLETE).
             */
            status?: string;
            /**
             * Beer order lines in this order.
             */
            beerOrderLines: Array<{
                /**
                 * Unique identifier for the beer order line. Read-only field generated by the system.
                 */
                readonly id?: number;
                /**
                 * Version number for optimistic locking. Read-only field incremented on each update.
                 */
                readonly version?: number;
                /**
                 * Date and time when the beer order line was created. Read-only field.
                 */
                readonly createdDate?: string;
                /**
                 * Date and time when the beer order line was last updated. Read-only field.
                 */
                readonly updateDate?: string;
                /**
                 * Identifier of the beer in this order line.
                 */
                beerId?: number;
                /**
                 * Name of the beer in this order line.
                 */
                beerName?: string;
                /**
                 * Style of the beer (e.g., ALE, PALE_ALE, IPA, etc.).
                 */
                beerStyle?: string;
                /**
                 * Universal Product Code of the beer.
                 */
                upc?: string;
                /**
                 * Quantity of beer ordered.
                 */
                orderQuantity: number;
                /**
                 * Quantity of beer allocated from inventory.
                 */
                quantityAllocated?: number;
                /**
                 * Status of the beer order line.
                 */
                status?: string;
            }>;
            /**
             * Shipments for this order.
             */
            shipments?: Array<paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema>;
        },
    ): CancelablePromise<paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/beer-orders',
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Get a beer order by ID
     * Returns a beer order by its ID.
     * @param id ID of the beer order
     * @returns paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema Successfully retrieved the beer order
     * @throws ApiError
     */
    public static getBeerOrderById(
        id: number,
    ): CancelablePromise<paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beer-orders/{id}',
            path: {
                'id': id,
            },
            errors: {
                401: `Unauthorized`,
                404: `Beer order not found`,
            },
        });
    }
    /**
     * Update a beer order
     * Updates an existing beer order. The ID in the path must match the ID in the request body.
     * @param id ID of the beer order
     * @param requestBody Beer order object with updated information
     * @returns paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema Successfully updated the beer order
     * @throws ApiError
     */
    public static updateBeerOrder(
        id: number,
        requestBody: paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema,
    ): CancelablePromise<paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/beer-orders/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
                404: `Beer order not found`,
            },
        });
    }
    /**
     * Delete a beer order
     * Deletes a beer order by its ID.
     * @param id ID of the beer order
     * @returns void
     * @throws ApiError
     */
    public static deleteBeerOrder(
        id: number,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/beer-orders/{id}',
            path: {
                'id': id,
            },
            errors: {
                401: `Unauthorized`,
                404: `Beer order not found`,
            },
        });
    }
    /**
     * Get all shipments for a beer order
     * Returns a list of all shipments for a specific beer order.
     * @param beerOrderId ID of the beer order to get shipments for
     * @returns paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema Successfully retrieved the list of shipments
     * @throws ApiError
     */
    public static getAllShipments(
        beerOrderId: number,
    ): CancelablePromise<Array<paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beer-orders/{beerOrderId}/shipments',
            path: {
                'beerOrderId': beerOrderId,
            },
            errors: {
                401: `Unauthorized`,
                404: `Beer order not found`,
            },
        });
    }
    /**
     * Create a new shipment for a beer order
     * Creates a new shipment for a specific beer order. The ID, version, createdDate, and updateDate fields will be ignored if provided.
     * @param beerOrderId ID of the beer order to create a shipment for
     * @param requestBody Shipment object to be created
     * @returns paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema Successfully created a new shipment
     * @throws ApiError
     */
    public static createShipment(
        beerOrderId: number,
        requestBody: {
            /**
             * Unique identifier for the beer order shipment. Read-only field generated by the system.
             */
            readonly id?: number;
            /**
             * Version number for optimistic locking. Read-only field incremented on each update.
             */
            readonly version?: number;
            /**
             * Date and time when the shipment was created. Read-only field.
             */
            readonly createdDate?: string;
            /**
             * Date and time when the shipment was last updated. Read-only field.
             */
            readonly updateDate?: string;
            /**
             * Date and time when the order was shipped.
             */
            shipmentDate: string;
            /**
             * Carrier used for the shipment (e.g., FedEx, UPS, DHL).
             */
            carrier?: string;
            /**
             * Tracking number for the shipment.
             */
            trackingNumber?: string;
        },
    ): CancelablePromise<paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/beer-orders/{beerOrderId}/shipments',
            path: {
                'beerOrderId': beerOrderId,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
                404: `Beer order not found`,
            },
        });
    }
    /**
     * Get a specific shipment for a beer order
     * Returns a specific shipment for a beer order.
     * @param beerOrderId ID of the beer order
     * @param shipmentId ID of the shipment to get
     * @returns paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema Successfully retrieved the shipment
     * @throws ApiError
     */
    public static getShipmentById(
        beerOrderId: number,
        shipmentId: number,
    ): CancelablePromise<paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beer-orders/{beerOrderId}/shipments/{shipmentId}',
            path: {
                'beerOrderId': beerOrderId,
                'shipmentId': shipmentId,
            },
            errors: {
                401: `Unauthorized`,
                404: `Beer order or shipment not found`,
            },
        });
    }
    /**
     * Update a specific shipment for a beer order
     * Updates a specific shipment for a beer order. The ID, version, createdDate, and updateDate fields will be ignored if provided.
     * @param beerOrderId ID of the beer order
     * @param shipmentId ID of the shipment to update
     * @param requestBody Shipment object to be updated
     * @returns paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema Successfully updated the shipment
     * @throws ApiError
     */
    public static updateShipment(
        beerOrderId: number,
        shipmentId: number,
        requestBody: paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema,
    ): CancelablePromise<paths_1api_1v1_1beer_orders_1_beerOrderId_1shipments_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/beer-orders/{beerOrderId}/shipments/{shipmentId}',
            path: {
                'beerOrderId': beerOrderId,
                'shipmentId': shipmentId,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
                404: `Beer order or shipment not found`,
            },
        });
    }
    /**
     * Delete a specific shipment for a beer order
     * Deletes a specific shipment for a beer order.
     * @param beerOrderId ID of the beer order
     * @param shipmentId ID of the shipment to delete
     * @returns void
     * @throws ApiError
     */
    public static deleteShipment(
        beerOrderId: number,
        shipmentId: number,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/beer-orders/{beerOrderId}/shipments/{shipmentId}',
            path: {
                'beerOrderId': beerOrderId,
                'shipmentId': shipmentId,
            },
            errors: {
                401: `Unauthorized`,
                404: `Beer order or shipment not found`,
            },
        });
    }
}
