/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema } from '../models/paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class BeerService {
    /**
     * Get all beers
     * Returns a paginated list of beers in the system with optional filtering by beer name and beer style.
     * @param beerName Filter beers by name (optional)
     * @param beerStyle Filter beers by style (optional)
     * @param page Page number (0-based, defaults to 0)
     * @param size Page size (defaults to 20)
     * @returns any Successfully retrieved the list of beers
     * @throws ApiError
     */
    public static getAllBeers(
        beerName?: string,
        beerStyle?: string,
        page?: number,
        size: number = 20,
    ): CancelablePromise<({
        /**
         * The page content
         */
        content?: Array<Record<string, any>>;
        /**
         * The pagination information
         */
        pageable?: {
            sort?: {
                sorted?: boolean;
                unsorted?: boolean;
                empty?: boolean;
            };
            offset?: number;
            pageNumber?: number;
            pageSize?: number;
            paged?: boolean;
            unpaged?: boolean;
        };
        /**
         * The total number of pages
         */
        totalPages?: number;
        /**
         * The total number of elements
         */
        totalElements?: number;
        /**
         * Whether this is the last page
         */
        last?: boolean;
        /**
         * The size of the page
         */
        size?: number;
        /**
         * The page number (0-based)
         */
        number?: number;
        sort?: {
            sorted?: boolean;
            unsorted?: boolean;
            empty?: boolean;
        };
        /**
         * The number of elements in this page
         */
        numberOfElements?: number;
        /**
         * Whether this is the first page
         */
        first?: boolean;
        /**
         * Whether the page is empty
         */
        empty?: boolean;
    } & {
        /**
         * The page content
         */
        content?: Array<paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema>;
    })> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beers',
            query: {
                'beerName': beerName,
                'beerStyle': beerStyle,
                'page': page,
                'size': size,
            },
            errors: {
                400: `Bad request`,
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Create a new beer
     * Creates a new beer in the system. The ID, version, createdDate, and updateDate fields will be ignored if provided.
     * @param requestBody Beer object to be created
     * @returns paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema Successfully created a new beer
     * @throws ApiError
     */
    public static createBeer(
        requestBody: {
            /**
             * Unique identifier for the beer. Read-only field generated by the system.
             */
            readonly id?: number;
            /**
             * Version number for optimistic locking. Read-only field incremented on each update.
             */
            readonly version?: number;
            /**
             * Date and time when the beer was created. Read-only field.
             */
            readonly createdDate?: string;
            /**
             * Date and time when the beer was last updated. Read-only field.
             */
            readonly updateDate?: string;
            /**
             * Name of the beer.
             */
            beerName: string;
            /**
             * Style of the beer (e.g., ALE, PALE_ALE, IPA, etc.).
             */
            beerStyle: string;
            /**
             * Universal Product Code, a 13-digit number assigned to each unique beer product by the Federal Bar Association.
             */
            upc: string;
            /**
             * Current quantity of beer available in stock.
             */
            quantityOnHand: number;
            /**
             * Description of the beer.
             */
            description?: string;
            /**
             * Price of the beer.
             */
            price: number;
        },
    ): CancelablePromise<paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/beers',
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Get a beer by ID
     * Returns a single beer identified by its ID.
     * @param id ID of the beer to operate on
     * @returns paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema Successfully retrieved the beer
     * @throws ApiError
     */
    public static getBeerById(
        id: number,
    ): CancelablePromise<paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/beers/{id}',
            path: {
                'id': id,
            },
            errors: {
                400: `Bad request`,
                401: `Unauthorized`,
                404: `Beer not found`,
            },
        });
    }
    /**
     * Update a beer
     * Updates an existing beer identified by its ID. The ID in the path must match the ID in the request body.
     * @param id ID of the beer to operate on
     * @param requestBody Updated beer object
     * @returns paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema Successfully updated the beer
     * @throws ApiError
     */
    public static updateBeer(
        id: number,
        requestBody: paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema,
    ): CancelablePromise<paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/beers/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
                404: `Beer not found`,
            },
        });
    }
    /**
     * Partially update a beer
     * Partially updates an existing beer identified by its ID. Only the provided fields will be updated.
     * @param id ID of the beer to operate on
     * @param requestBody Partial beer object with only the fields to update
     * @returns paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema Successfully updated the beer
     * @throws ApiError
     */
    public static patchBeer(
        id: number,
        requestBody: {
            /**
             * Unique identifier for the beer. Read-only field generated by the system.
             */
            readonly id?: number;
            /**
             * Version number for optimistic locking. Read-only field incremented on each update.
             */
            readonly version?: number;
            /**
             * Date and time when the beer was created. Read-only field.
             */
            readonly createdDate?: string;
            /**
             * Date and time when the beer was last updated. Read-only field.
             */
            readonly updateDate?: string;
            /**
             * Name of the beer.
             */
            beerName?: string;
            /**
             * Style of the beer (e.g., ALE, PALE_ALE, IPA, etc.).
             */
            beerStyle?: string;
            /**
             * Universal Product Code, a 13-digit number assigned to each unique beer product by the Federal Bar Association.
             */
            upc?: string;
            /**
             * Current quantity of beer available in stock.
             */
            quantityOnHand?: number;
            /**
             * Description of the beer.
             */
            description?: string;
            /**
             * Price of the beer.
             */
            price?: number;
        },
    ): CancelablePromise<paths_1api_1v1_1beers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/beers/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request`,
                401: `Unauthorized`,
                404: `Beer not found`,
            },
        });
    }
    /**
     * Delete a beer
     * Deletes a beer identified by its ID.
     * @param id ID of the beer to operate on
     * @returns void
     * @throws ApiError
     */
    public static deleteBeer(
        id: number,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/beers/{id}',
            path: {
                'id': id,
            },
            errors: {
                400: `Bad request`,
                401: `Unauthorized`,
                404: `Beer not found`,
            },
        });
    }
}
