/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema } from '../models/paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema';
import type { paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema } from '../models/paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class CustomerService {
    /**
     * Get all customers
     * Returns a list of all customers in the system.
     * @returns paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema Successfully retrieved the list of customers
     * @throws ApiError
     */
    public static getAllCustomers(): CancelablePromise<Array<paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/customers',
            errors: {
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Create a new customer
     * Creates a new customer in the system. The ID, version, createdDate, and updateDate fields will be ignored if provided.
     * @param requestBody Customer object to be created
     * @returns paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema Successfully created a new customer
     * @throws ApiError
     */
    public static createCustomer(
        requestBody: {
            /**
             * Unique identifier for the customer. Read-only field generated by the system.
             */
            readonly id?: number;
            /**
             * Version number for optimistic locking. Read-only field incremented on each update.
             */
            readonly version?: number;
            /**
             * Date and time when the customer was created. Read-only field.
             */
            readonly createdDate?: string;
            /**
             * Date and time when the customer was last updated. Read-only field.
             */
            readonly updateDate?: string;
            /**
             * Name of the customer.
             */
            name: string;
            /**
             * Email address of the customer.
             */
            email?: string;
            /**
             * Phone number of the customer.
             */
            phoneNumber?: string;
            /**
             * First line of the customer's address.
             */
            addressLine1: string;
            /**
             * Second line of the customer's address (optional).
             */
            addressLine2?: string;
            /**
             * City of the customer's address.
             */
            city: string;
            /**
             * State or province of the customer's address.
             */
            state: string;
            /**
             * Postal code of the customer's address.
             */
            postalCode: string;
            /**
             * Beer orders placed by this customer.
             */
            readonly beerOrders?: Array<paths_1api_1v1_1beer_orders_post_requestBody_content_application_1json_schema>;
        },
    ): CancelablePromise<paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/customers',
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error`,
                401: `Unauthorized`,
            },
        });
    }
    /**
     * Get a customer by ID
     * Returns a single customer by ID.
     * @param id ID of the customer to operate on
     * @returns paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema Successfully retrieved the customer
     * @throws ApiError
     */
    public static getCustomerById(
        id: number,
    ): CancelablePromise<paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/customers/{id}',
            path: {
                'id': id,
            },
            errors: {
                401: `Unauthorized`,
                404: `Customer not found`,
            },
        });
    }
    /**
     * Update an existing customer
     * Updates an existing customer in the system. The ID in the path must match the ID in the request body.
     * @param id ID of the customer to operate on
     * @param requestBody Customer object with updated fields
     * @returns paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema Successfully updated the customer
     * @throws ApiError
     */
    public static updateCustomer(
        id: number,
        requestBody: paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema,
    ): CancelablePromise<paths_1api_1v1_1customers_post_requestBody_content_application_1json_schema> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/customers/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad request - validation error or ID mismatch`,
                401: `Unauthorized`,
                404: `Customer not found`,
            },
        });
    }
    /**
     * Delete a customer
     * Deletes a customer from the system.
     * @param id ID of the customer to operate on
     * @returns void
     * @throws ApiError
     */
    public static deleteCustomer(
        id: number,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/customers/{id}',
            path: {
                'id': id,
            },
            errors: {
                401: `Unauthorized`,
                404: `Customer not found`,
            },
        });
    }
}
