/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BeerOrderLineDto } from './BeerOrderLineDto';
import type { BeerOrderShipmentDto } from './BeerOrderShipmentDto';
/**
 * Data Transfer Object for BeerOrder entities
 */
export type BeerOrderDto = {
    /**
     * Unique identifier for the beer order. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the beer order was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the beer order was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Reference information from customer.
     */
    customerRef?: string;
    /**
     * Customer associated with the order (required by API).
     */
    customer?: import('./CustomerDto').CustomerDto;
    /**
     * Payment amount for the order.
     */
    paymentAmount: number;
    /**
     * Status of the order (e.g., NEW, PAID, CANCELLED, INPROCESS, COMPLETE).
     */
    status?: string;
    /**
     * Beer order lines in this order.
     */
    beerOrderLines: Array<BeerOrderLineDto>;
    /**
     * Shipments for this order.
     */
    shipments?: Array<BeerOrderShipmentDto>;
};

